name: Build and Release

on:
  push:
    tags: ['v*']
  release:
    types: [published]

jobs:
  build-deb:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Build DEB package
      run: |
        chmod +x build.sh
        ./build.sh
        
    - name: Upload DEB artifact
      uses: actions/upload-artifact@v4
      with:
        name: site-scanner-deb
        path: site-scanner.deb
        
    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: site-scanner.deb
